# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: add_staged_files_to_index
        name: add_staged_files_to_index
        entry: python -m utils.add_recently_modified_links
        language: system
        files: ^.*.md$
