site_name: Dhruv's Wiki
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: deep orange
  features:
    - instant
    - tabs
  favicon: assets/images/favicon.png
  icon:
    logo: fontawesome/solid/code
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crunchysonnets
    - icon: fontawesome/brands/github
      link: https://github.com/dhth
    - icon: fontawesome/regular/compass
      link: https://dhruvs.space
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/extra.css
# extra_javascript:
#   - assets/extra.js
