git mv docs/tools/other/index.md docs/tools/other/other.md
git mv docs/tools/mac/applescript/wiki/index.md docs/tools/mac/applescript/wiki/applescript-wiki.md
git mv docs/tools/mac/applescript/index.md docs/tools/mac/applescript/applescript.md
git mv docs/tools/mac/index.md docs/tools/mac/mac.md
git mv docs/tools/mac/keyboard-maestro/index.md docs/tools/mac/keyboard-maestro/keyboard-maestro.md
git mv docs/tools/mac/alfred/workflows/wiki/index.md docs/tools/mac/alfred/workflows/wiki/workflows-wiki.md
git mv docs/tools/mac/alfred/workflows/my-workflows/spotify/index.md docs/tools/mac/alfred/workflows/my-workflows/spotify/spotify.md
git mv docs/tools/mac/alfred/workflows/my-workflows/index.md docs/tools/mac/alfred/workflows/my-workflows/my-workflows.md
git mv docs/tools/mac/alfred/workflows/index.md docs/tools/mac/alfred/workflows/workflows.md
git mv docs/tools/mac/alfred/index.md docs/tools/mac/alfred/alfred.md
git mv docs/tools/mac/karabiner/goku/index.md docs/tools/mac/karabiner/goku/goku.md
git mv docs/tools/mac/karabiner/index.md docs/tools/mac/karabiner/karabiner.md
git mv docs/tools/mac/keyboard-shortcuts/index.md docs/tools/mac/keyboard-shortcuts/keyboard-shortcuts.md
git mv docs/tools/index.md docs/tools/tools.md
git mv docs/tools/programming/vim/vimscript/index.md docs/tools/programming/vim/vimscript/vimscript.md
git mv docs/tools/programming/vim/plugins/index.md docs/tools/programming/vim/plugins/plugins.md
git mv docs/tools/programming/vim/plugins/coc/language-servers/index.md docs/tools/programming/vim/plugins/coc/language-servers/language-servers.md
git mv docs/tools/programming/vim/plugins/coc/index.md docs/tools/programming/vim/plugins/coc/coc.md
git mv docs/tools/programming/vim/resources/index.md docs/tools/programming/vim/resources/vim-resources.md
git mv docs/tools/programming/vim/index.md docs/tools/programming/vim/vim.md
git mv docs/tools/programming/vim/neovim/index.md docs/tools/programming/vim/neovim/neovim.md
git mv docs/tools/programming/vim/neovim/plugin-development/index.md docs/tools/programming/vim/neovim/plugin-development/plugin-development.md
git mv docs/tools/programming/vim/themes/index.md docs/tools/programming/vim/themes/themes.md
git mv docs/tools/programming/vim/vim-wiki/index.md docs/tools/programming/vim/vim-wiki/vim-wiki.md
git mv docs/tools/programming/curl/index.md docs/tools/programming/curl/curl.md
git mv docs/tools/programming/unix/bash/index.md docs/tools/programming/unix/bash/bash.md
git mv docs/tools/programming/unix/utilities/coreutils/ghead/index.md docs/tools/programming/unix/utilities/coreutils/ghead/ghead.md
git mv docs/tools/programming/unix/utilities/coreutils/index.md docs/tools/programming/unix/utilities/coreutils/coreutils.md
git mv docs/tools/programming/unix/utilities/index.md docs/tools/programming/unix/utilities/utilities.md
git mv docs/tools/programming/unix/index.md docs/tools/programming/unix/unix.md
git mv docs/tools/programming/unix/commands/awk/index.md docs/tools/programming/unix/commands/awk/awk.md
git mv docs/tools/programming/unix/commands/index.md docs/tools/programming/unix/commands/commands.md
git mv docs/tools/programming/index.md docs/tools/programming/programming.md
git mv docs/tools/programming/tmux/index.md docs/tools/programming/tmux/tmux.md
git mv docs/tools/programming/jq/index.md docs/tools/programming/jq/jq.md
git mv docs/tools/programming/intellij/index.md docs/tools/programming/intellij/intellij.md
git mv docs/tools/programming/git/wiki/index.md docs/tools/programming/git/wiki/git-wiki.md
git mv docs/tools/programming/git/index.md docs/tools/programming/git/git.md
git mv docs/computer-science/roadmap/index.md docs/computer-science/roadmap/roadmap.md
git mv docs/computer-science/leetcode/index.md docs/computer-science/leetcode/leetcode.md
git mv docs/computer-science/wiki/index.md docs/computer-science/wiki/computer-science-wiki.md
git mv docs/computer-science/books/mastering-algorithms-in-c/index.md docs/computer-science/books/mastering-algorithms-in-c/mastering-algorithms-in-c.md
git mv docs/computer-science/books/index.md docs/computer-science/books/books.md
git mv docs/computer-science/books/the-algorithm-design-manual/index.md docs/computer-science/books/the-algorithm-design-manual/the-algorithm-design-manual.md
git mv docs/computer-science/stories/index.md docs/computer-science/stories/stories.md
git mv docs/computer-science/courses/cs61b-data-structures/asymptotics/index.md docs/computer-science/courses/cs61b-data-structures/asymptotics/asymptotics.md
git mv docs/computer-science/courses/cs61b-data-structures/range-searching-and-multi-dimensional-data/index.md docs/computer-science/courses/cs61b-data-structures/range-searching-and-multi-dimensional-data/range-searching-and-multi-dimensional-data.md
git mv docs/computer-science/courses/cs61b-data-structures/index.md docs/computer-science/courses/cs61b-data-structures/cs61b-data-structures.md
git mv docs/computer-science/courses/cs61b-data-structures/b-trees/index.md docs/computer-science/courses/cs61b-data-structures/b-trees/b-trees.md
git mv docs/computer-science/courses/cs61b-data-structures/heaps-and-primary-queues/index.md docs/computer-science/courses/cs61b-data-structures/heaps-and-primary-queues/heaps-and-primary-queues.md
git mv docs/computer-science/courses/from-nand-to-tetris-part-1/index.md docs/computer-science/courses/from-nand-to-tetris-part-1/from-nand-to-tetris-part-1.md
git mv docs/computer-science/courses/cs61c-machine-structures/index.md docs/computer-science/courses/cs61c-machine-structures/cs61c-machine-structures.md
git mv docs/computer-science/courses/the-missing-semester/index.md docs/computer-science/courses/the-missing-semester/the-missing-semester.md
git mv docs/computer-science/courses/index.md docs/computer-science/courses/courses.md
git mv docs/computer-science/index.md docs/computer-science/computer-science.md
git mv docs/computer-science/computer-networking/wiki/index.md docs/computer-science/computer-networking/wiki/computer-networking-wiki.md
git mv docs/computer-science/computer-networking/courses/index.md docs/computer-science/computer-networking/courses/courses.md
git mv docs/computer-science/computer-networking/courses/the-bits-and-bytes-of-computer-networking/week-1/index.md docs/computer-science/computer-networking/courses/the-bits-and-bytes-of-computer-networking/week-1/week-1.md
git mv docs/computer-science/computer-networking/courses/the-bits-and-bytes-of-computer-networking/index.md docs/computer-science/computer-networking/courses/the-bits-and-bytes-of-computer-networking/the-bits-and-bytes-of-computer-networking.md
git mv docs/computer-science/computer-networking/index.md docs/computer-science/computer-networking/computer-networking.md
git mv docs/other/courses/index.md docs/other/courses/courses.md
git mv docs/other/courses/investment-and-portfolio-management/index.md docs/other/courses/investment-and-portfolio-management/investment-and-portfolio-management.md
git mv docs/other/courses/investment-and-portfolio-management/global-financial-markets-and-instruments/week-1/index.md docs/other/courses/investment-and-portfolio-management/global-financial-markets-and-instruments/week-1/week-1.md
git mv docs/other/courses/investment-and-portfolio-management/global-financial-markets-and-instruments/index.md docs/other/courses/investment-and-portfolio-management/global-financial-markets-and-instruments/global-financial-markets-and-instruments.md
git mv docs/other/index.md docs/other/other.md
git mv docs/other/coffee/index.md docs/other/coffee/coffee.md
git mv docs/other/digital-gardens/index.md docs/other/digital-gardens/digital-gardens.md
git mv docs/books/index.md docs/books/books.md
git mv docs/programming/docker/multi-architecture-builds/index.md docs/programming/docker/multi-architecture-builds/multi-architecture-builds.md
git mv docs/programming/docker/debugging/index.md docs/programming/docker/debugging/debugging.md
git mv docs/programming/docker/index.md docs/programming/docker/docker.md
git mv docs/programming/go/index.md docs/programming/go/go.md
git mv docs/programming/python/flask/index.md docs/programming/python/flask/flask.md
git mv docs/programming/python/packaging/index.md docs/programming/python/packaging/packaging.md
git mv docs/programming/python/databases/sqlalchemy/essential-sqlalchemy/index.md docs/programming/python/databases/sqlalchemy/essential-sqlalchemy/essential-sqlalchemy.md
git mv docs/programming/python/databases/sqlalchemy/index.md docs/programming/python/databases/sqlalchemy/sqlalchemy.md
git mv docs/programming/python/databases/index.md docs/programming/python/databases/databases.md
git mv docs/programming/python/pytest/index.md docs/programming/python/pytest/pytest.md
git mv docs/programming/python/pytest/testing-with-pytest/index.md docs/programming/python/pytest/testing-with-pytest/testing-with-pytest.md
git mv docs/programming/python/debugging/index.md docs/programming/python/debugging/debugging.md
git mv docs/programming/python/setup/pyenv/index.md docs/programming/python/setup/pyenv/pyenv.md
git mv docs/programming/python/setup/pip/index.md docs/programming/python/setup/pip/pip.md
git mv docs/programming/python/setup/index.md docs/programming/python/setup/setup.md
git mv docs/programming/python/wiki/index.md docs/programming/python/wiki/python-wiki.md
git mv docs/programming/python/books/python-tricks/index.md docs/programming/python/books/python-tricks/python-tricks.md
git mv docs/programming/python/books/index.md docs/programming/python/books/books.md
git mv docs/programming/python/typing/index.md docs/programming/python/typing/typing.md
git mv docs/programming/python/index.md docs/programming/python/python.md
git mv docs/programming/python/profiling/index.md docs/programming/python/profiling/profiling.md
git mv docs/programming/python/fastapi/index.md docs/programming/python/fastapi/fastapi.md
git mv docs/programming/python/asyncio/index.md docs/programming/python/asyncio/asyncio.md
git mv docs/programming/python/logging/index.md docs/programming/python/logging/logging.md
git mv docs/programming/web/apis/index.md docs/programming/web/apis/apis.md
git mv docs/programming/web/security/json-web-token/index.md docs/programming/web/security/json-web-token/json-web-token.md
git mv docs/programming/web/security/index.md docs/programming/web/security/security.md
git mv docs/programming/web/index.md docs/programming/web/web.md
git mv docs/programming/web/graphql/index.md docs/programming/web/graphql/graphql.md
git mv docs/programming/java/maven/index.md docs/programming/java/maven/maven.md
git mv docs/programming/java/index.md docs/programming/java/java.md
git mv docs/programming/miscellaneous/index.md docs/programming/miscellaneous/miscellaneous.md
git mv docs/programming/lua/index.md docs/programming/lua/lua.md
git mv docs/programming/exercism/index.md docs/programming/exercism/exercism.md
git mv docs/programming/index.md docs/programming/programming.md
git mv docs/programming/aws/cdk/api-gateway/wiki/index.md docs/programming/aws/cdk/api-gateway/wiki/api-gateway-wiki.md
git mv docs/programming/aws/cdk/api-gateway/index.md docs/programming/aws/cdk/api-gateway/api-gateway.md
git mv docs/programming/aws/cdk/wiki/index.md docs/programming/aws/cdk/wiki/cdk-wiki.md
git mv docs/programming/aws/cdk/wiki/cdk-day/index.md docs/programming/aws/cdk/wiki/cdk-day/cdk-day.md
git mv docs/programming/aws/cdk/ecs/ecs-patterns/index.md docs/programming/aws/cdk/ecs/ecs-patterns/ecs-patterns.md
git mv docs/programming/aws/cdk/ecs/index.md docs/programming/aws/cdk/ecs/ecs.md
git mv docs/programming/aws/cdk/cicd/index.md docs/programming/aws/cdk/cicd/cicd.md
git mv docs/programming/aws/cdk/iam/index.md docs/programming/aws/cdk/iam/iam.md
git mv docs/programming/aws/cdk/index.md docs/programming/aws/cdk/cdk.md
git mv docs/programming/aws/cdk/python-api-reference/index.md docs/programming/aws/cdk/python-api-reference/python-api-reference.md
git mv docs/programming/aws/cdk/lambda/index.md docs/programming/aws/cdk/lambda/lambda.md
git mv docs/programming/aws/cdk/vpc/index.md docs/programming/aws/cdk/vpc/vpc.md
git mv docs/programming/aws/cloudbuild/index.md docs/programming/aws/cloudbuild/cloudbuild.md
git mv docs/programming/aws/ecs/index.md docs/programming/aws/ecs/ecs.md
git mv docs/programming/aws/index.md docs/programming/aws/aws.md
git mv docs/programming/aws/certifications/index.md docs/programming/aws/certifications/certifications.md
git mv docs/programming/aws/certifications/solutions-architect/courses/index.md docs/programming/aws/certifications/solutions-architect/courses/courses.md
git mv docs/programming/aws/certifications/solutions-architect/courses/stephane-maarek/index.md docs/programming/aws/certifications/solutions-architect/courses/stephane-maarek/stephane-maarek.md
git mv docs/programming/aws/certifications/solutions-architect/index.md docs/programming/aws/certifications/solutions-architect/solutions-architect.md
git mv docs/programming/aws/vpc/index.md docs/programming/aws/vpc/vpc.md
git mv docs/programming/aws/load-balancers/index.md docs/programming/aws/load-balancers/load-balancers.md
git mv docs/programming/aws/load-balancers/network-load-balancers/index.md docs/programming/aws/load-balancers/network-load-balancers/network-load-balancers.md
git mv docs/programming/aws/cloudformation/index.md docs/programming/aws/cloudformation/cloudformation.md
git mv docs/programming/interviewing/index.md docs/programming/interviewing/interviewing.md
git mv docs/programming/javascript/typescript/index.md docs/programming/javascript/typescript/typescript.md
git mv docs/programming/javascript/index.md docs/programming/javascript/javascript.md
git mv docs/programming/javascript/freecodecamp/2-javascript-algorithms-and-data-structures/index.md docs/programming/javascript/freecodecamp/2-javascript-algorithms-and-data-structures/2-javascript-algorithms-and-data-structures.md
git mv docs/programming/javascript/freecodecamp/3-frontend-libraries/index.md docs/programming/javascript/freecodecamp/3-frontend-libraries/3-frontend-libraries.md
git mv docs/programming/javascript/freecodecamp/1-responsive-web-design/index.md docs/programming/javascript/freecodecamp/1-responsive-web-design/1-responsive-web-design.md
git mv docs/programming/javascript/freecodecamp/4-data-visualization/index.md docs/programming/javascript/freecodecamp/4-data-visualization/4-data-visualization.md
git mv docs/programming/javascript/freecodecamp/index.md docs/programming/javascript/freecodecamp/freecodecamp.md
git mv docs/programming/javascript/freecodecamp/5-apis-and-microservices/index.md docs/programming/javascript/freecodecamp/5-apis-and-microservices/5-apis-and-microservices.md
git mv docs/on-my-mind/index.md docs/on-my-mind/on-my-mind.md
git mv docs/programming/java/maven/01-basics.md  docs/programming/java/maven/maven-basics.md
git mv docs/programming/javascript/typescript/basics.md docs/programming/javascript/typescript/typescript-basics.md
git mv docs/programming/python/profiling/basics.md docs/programming/python/profiling/profiling-basics.md
git mv docs/tools/programming/unix/bash/basics.md docs/tools/programming/unix/bash/bash-basics.md
git mv docs/programming/aws/cdk/01-resources.md docs/programming/aws/cdk/cdk-resources.md
git mv docs/programming/docker/02-resources.md docs/programming/docker/docker-resources.md
git mv docs/programming/interviewing/01-resources.md docs/programming/interviewing/interviewing-resources.md
git mv docs/programming/python/01-resources.md docs/programming/python/python-resources.md
git mv docs/programming/web/graphql/01-resources.md docs/programming/web/graphql/graphql-resources.md
git mv docs/tools/programming/git/resources.md docs/tools/programming/git/git-resources.md
git mv docs/tools/programming/intellij/02-resources.md docs/tools/programming/intellij/intellij-resources.md
