[build]
  base = "_layouts/"
  publish = "public/"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.22.17"
  NODE_VERSION = "v16.14.0"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
