[build]
  base = "_layouts/"
  publish = "public/"
  command = "npm run build"
  ignore = "/bin/false"
[build.environment]
  YARN_VERSION = "1.22.17"
  NODE_VERSION = "v16.14.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
